### ISSUE TITLE
老哥以前在小米工作过么~

### ISSUE THREAD

**Issue by TIGERB** [wulijun/go-php-serialize#8]
老哥以前在小米工作过么~

**Comment by bluntdel** [comment]
> 老哥以前在小米工作过么~

老哥你在小米做电商，是有品吗

**Comment by bluntdel** [comment]
> > 老哥以前在小米工作过么~
> 
> 老哥你在小米做电商，是有品吗

看了老哥following，有一些熟悉的面孔。看来技术栈挺相似。。

**Comment by TIGERB** [comment]
哈哈哈 我在小米网

在以前go代码看见了这个包 哈哈哈哈哈
